import { useEffect, useState } from 'react';
import type { AiSettings as Config, AiSettingsView } from '../shared/report-contracts';
import { errorMessage, request } from './api';
export default function AiSettings({ onDirty }: { onDirty: (value: boolean) => void }) {
  const [saved, setSaved] = useState<AiSettingsView | null>(null); const [draft, setDraft] = useState<Config | null>(null); const [key, setKey] = useState(''); const [clear, setClear] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<unknown>(null); const [notice, setNotice] = useState('');
  const fields = (value: AiSettingsView): Config => ({ mode: value.mode, model: value.model, max_output_tokens: value.max_output_tokens, daily_call_limit: value.daily_call_limit });
  const dirty = !!draft && !!saved && (JSON.stringify(draft) !== JSON.stringify(fields(saved)) || !!key || clear);
  useEffect(() => { onDirty(dirty || busy); }, [dirty, busy, onDirty]); useEffect(() => () => onDirty(false), [onDirty]);
  useEffect(() => { const handler = (event: BeforeUnloadEvent) => { if (dirty || busy) { event.preventDefault(); event.returnValue = ''; } }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler); }, [dirty, busy]);
  async function load() { try { const data = await request<AiSettingsView>('/api/ai/settings'); setSaved(data); setDraft(fields(data)); setKey(''); setClear(false); setError(null); } catch (failure) { setError(failure); } }
  useEffect(() => { void load(); }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); if (!draft || !saved || busy) return; setBusy(true); setError(null); setNotice(''); try { const data = await request<AiSettingsView>('/api/ai/settings', 'PUT', { revision: saved.revision, settings: draft, ...(key ? { key } : {}), clear_key: clear }); setSaved(data); setDraft(fields(data)); setKey(''); setClear(false); setNotice('AI 设置已保存；生成报告时才会发送业务摘要。'); } catch (failure) { setError(failure); } finally { setBusy(false); } }
  async function test() { if (busy) return; setBusy(true); setError(null); setNotice(''); try { const result = await request<{ message: string }>('/api/ai/test', 'POST', {}); setNotice(result.message); const data = await request<AiSettingsView>('/api/ai/settings'); setSaved(data); } catch (failure) { setError(failure); } finally { setBusy(false); } }
  return <section className="settings-section ai-settings"><h2>AI 经营助理</h2><p>先使用本地摘要也能完成记录与结算。在线模式只接 OpenAI 官方 API；模型名称需与你的 API 账户权限对应。</p>{!!error && <div className="inline-error" role="alert">{errorMessage(error)}<button className="button-quiet" onClick={() => void load()}>放弃修改，读取最新配置</button></div>}{draft && saved && <form onSubmit={event => void save(event)}><fieldset disabled={busy}><div className="form-grid"><label className="field"><span>分析服务</span><select value={draft.mode} onChange={event => setDraft({ ...draft, mode: event.target.value as Config['mode'] })}><option value="local">本地规则摘要（离线）</option><option value="openai">OpenAI 官方 API</option></select></label><label className="field"><span>API 模型名称（不是服务商名称）</span><input autoComplete="off" required={draft.mode === 'openai'} value={draft.model} placeholder="填写所选服务账户提供的具体模型 ID" onChange={event => setDraft({ ...draft, model: event.target.value })} /></label><label className="field span-two"><span>{saved.has_key ? '替换 API Key（留空保留）' : 'API Key（可稍后配置）'}</span><input type="password" autoComplete="new-password" value={key} disabled={clear} onChange={event => setKey(event.target.value)} /><small>密钥使用 Windows 当前用户保护加密，保存后不回显。不会存入浏览器或业务 SQLite。不要在聊天中粘贴密钥。</small></label><label className="field"><span>单次输出 token 上限</span><input type="number" min={800} max={6000} required value={draft.max_output_tokens} onChange={event => setDraft({ ...draft, max_output_tokens: Number(event.target.value) })} /></label><label className="field"><span>每日 API 尝试次数上限</span><input type="number" min={1} max={100} required value={draft.daily_call_limit} onChange={event => setDraft({ ...draft, daily_call_limit: Number(event.target.value) })} /></label></div>{saved.has_key && <label className="checkbox-label"><input type="checkbox" checked={clear} onChange={event => { setClear(event.target.checked); setKey(''); }} />清除本应用保存的密钥（不修改系统环境变量）</label>}</fieldset><p className="day-subtle">{draft.mode === 'local' && '当前为本地规则模式；填写模型或保存密钥不会自动开启在线 AI。'}今天已尝试 {saved.calls_today} 次；连接测试和失败重试也计入。费用因模型与输入量而异，此处不是金额预算。每次生成最多尝试两次。</p><div className="score-actions"><button className="button-primary" disabled={!dirty || busy}>{busy ? '处理中…' : '保存 AI 设置'}</button><button type="button" className="button-secondary" disabled={busy || dirty || saved.mode !== 'openai' || !saved.has_key} onClick={() => void test()}>测试连接（仅发送合成资料）</button></div>{notice && <p role="status" className="day-subtle">{notice}</p>}</form>}</section>;
}
